name: gendiff

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install project
      run: |
        make install
    - name: Lint with flake8
      run: |
        make lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.5.7
      env:
        CC_TEST_REPORTER_ID: 8cb5b5018dba6a9d23f40176d61c8a593d56bc32aa05d9ce7e4699655d82fb54
      with:
        coverageCommand: make test
        debug: true
